namespace Server
{
    runtimeclass Reader
    {
        Reader();
        String P0 { get; };
        String P1 { get; };
        String P2 { get; };
        String P3 { get; };
        String P4 { get; };
        String P5 { get; };
        String P6 { get; };
        String P7 { get; };
        String P8 { get; };
        String P9 { get; };
        String P10 { get; };
        String P11 { get; };
        String P12 { get; };
        String P13 { get; };
        String P14 { get; };
        String P15 { get; };
        String P16 { get; };
        String P17 { get; };
        String P18 { get; };
        String P19 { get; };
        String P20 { get; };
        String P21 { get; };
        String P22 { get; };
        String P23 { get; };
        String P24 { get; };
        String P25 { get; };
        String P26 { get; };
        String P27 { get; };
        String P28 { get; };
        String P29 { get; };
        String P30 { get; };
        String P31 { get; };
        String P32 { get; };
        String P33 { get; };
        String P34 { get; };
        String P35 { get; };
        String P36 { get; };
        String P37 { get; };
        String P38 { get; };
        String P39 { get; };
        String P40 { get; };
        String P41 { get; };
        String P42 { get; };
        String P43 { get; };
        String P44 { get; };
        String P45 { get; };
        String P46 { get; };
        String P47 { get; };
        String P48 { get; };
        String P49 { get; };
        String P50 { get; };
        String P51 { get; };
        String P52 { get; };
        String P53 { get; };
        String P54 { get; };
        String P55 { get; };
        String P56 { get; };
        String P57 { get; };
        String P58 { get; };
        String P59 { get; };
        String P60 { get; };
        String P61 { get; };
        String P62 { get; };
        String P63 { get; };
        String P64 { get; };
        String P65 { get; };
        String P66 { get; };
        String P67 { get; };
        String P68 { get; };
        String P69 { get; };
        String P70 { get; };
        String P71 { get; };
        String P72 { get; };
        String P73 { get; };
        String P74 { get; };
        String P75 { get; };
        String P76 { get; };
        String P77 { get; };
        String P78 { get; };
        String P79 { get; };
        String P80 { get; };
        String P81 { get; };
        String P82 { get; };
        String P83 { get; };
        String P84 { get; };
        String P85 { get; };
        String P86 { get; };
        String P87 { get; };
        String P88 { get; };
        String P89 { get; };
        String P90 { get; };
        String P91 { get; };
        String P92 { get; };
        String P93 { get; };
        String P94 { get; };
        String P95 { get; };
        String P96 { get; };
        String P97 { get; };
        String P98 { get; };
        String P99 { get; };
        String P100 { get; };
    }

    runtimeclass Writer
    {
        Writer();
        String P0;
        String P1;
        String P2;
        String P3;
        String P4;
        String P5;
        String P6;
        String P7;
        String P8;
        String P9;
        String P10;
        String P11;
        String P12;
        String P13;
        String P14;
        String P15;
        String P16;
        String P17;
        String P18;
        String P19;
        String P20;
        String P21;
        String P22;
        String P23;
        String P24;
        String P25;
        String P26;
        String P27;
        String P28;
        String P29;
        String P30;
        String P31;
        String P32;
        String P33;
        String P34;
        String P35;
        String P36;
        String P37;
        String P38;
        String P39;
        String P40;
        String P41;
        String P42;
        String P43;
        String P44;
        String P45;
        String P46;
        String P47;
        String P48;
        String P49;
        String P50;
        String P51;
        String P52;
        String P53;
        String P54;
        String P55;
        String P56;
        String P57;
        String P58;
        String P59;
        String P60;
        String P61;
        String P62;
        String P63;
        String P64;
        String P65;
        String P66;
        String P67;
        String P68;
        String P69;
        String P70;
        String P71;
        String P72;
        String P73;
        String P74;
        String P75;
        String P76;
        String P77;
        String P78;
        String P79;
        String P80;
        String P81;
        String P82;
        String P83;
        String P84;
        String P85;
        String P86;
        String P87;
        String P88;
        String P89;
        String P90;
        String P91;
        String P92;
        String P93;
        String P94;
        String P95;
        String P96;
        String P97;
        String P98;
        String P99;
        String P100;
    }
}
